### ISSUE TITLE
NPC.GetGlobalNPC returns exception on world load

### ISSUE THREAD

**Issue by w-man12** [bluemagic123/tModLoader#4712]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

So I've set up a system that respawns certain npcs in Modsystem.LoadWorldData, and on the first tick they exist, they run Targeting code that references an instanced GlobalNPC. When attempting to call the NPC.GetGlobalNPC, there are occasional error messages, EDIT TryGetGlobalNPC does function properly, but NPC.GetGlobalNPC still ocassionally fails when the world is initially loaded

### Log File

[client.log](https://github.com/user-attachments/files/21201760/client.log)
The most recent error is relating to this issue, from attempting to run NPC.GetGlobalNPC<T>()

### Steps to reproduce

Step 1: Spawn an NPC through ModSystem.LoadWorldData
Step 2: Run NPC.GetGlobalNPC<>() on another NPC within the first NPC's AI() Instanced Global NPC
I am unsure of the exact specifics but Currently the Respawned NPCs cycle through all active NPCs when the world loads

### Reproduction frequency

This issue occurs with low constancy whenever the world initially loads.
Note: Following the posting of this thread I have been unable to recreate the issue, so it seems to be incredibly rare happening once every maybe 20 or 30 world loads, I've only reported this because I encountered it twice in quick succession.

**Comment by JavidPack** [comment]
This needs a minimal reproduction code example.

**Comment by w-man12** [comment]
Okay so on further investigation TryGetGlobalNPC does work but running npc.GetGlobalNPC early enough in the world does lead to occasional exceptions, apologies for any inconvenience

**Comment by JavidPack** [comment]
You shouldn't be seeing exceptions in that case either.

**Comment by w-man12** [comment]
That is definitely a bug then as I have been getting them rarely on world load ever since I implemented the GetGlobalNPC, here is another instance from earlier today [client.log](https://github.com/user-attachments/files/21201989/client.log), again I am unsure of the exact cause, maybe something to do with lag causing a delay in the GlobalNPC initializing? I'm not really familiar with tmod's backend enough to point out a possible cause. 

The code causing the error looks like:
```cs
foreach (NPC npc in SRPTerraria.AllNonParasites)
{
    if (npc != null && npc.dontTakeDamage != true)
    {
        if (npc.Distance(NPC.Center) * npc.GetGlobalNPC<SRPTInstancedGlobalNPC>().ParasiteAgroMult < ValidTargetDistance)
        {
            if (npc.whoAmI != NPC.whoAmI && !(npc.GetAmpOf<CoTHDebuff>() >= 3))
            {
                bool isValid = true;
                if (npc.boss || NPCID.Sets.ShouldBeCountedAsBoss[npc.type])
                    isValid = false;
                if (!npc.chaseable)
                    isValid = false;
                if (isValid)
                {
                    if (Collision.CanHitLine(NPC.Center, 0, 0, npc.Center, 0, 0) || npc.Distance(NPC.Center) < SearchRange * Wallsightmult.ApplyTo(SearchRangeReduction))
                    {
                        ClosestValidNPCTarget = npc;
                        ValidTargetDistance = npc.Distance(NPC.Center) * npc.GetGlobalNPC<SRPTInstancedGlobalNPC>().ParasiteAgroMult;
                    }
                }
            }
        }
    }
}
```

AllNonParasites is a custom iterator similar to Main.ActiveNPCs, and aside from the mentioned occasional exceptions on world load the code runs perfectly fine even when run every tick dozens of times.

**Comment by w-man12** [comment]
Again this should probably be low on the priority list it seems to be VERY infrequent

**Comment by Chicken-Bones** [comment]
```
[14:28:22.523] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.Collections.Generic.KeyNotFoundException: SRPTerraria.Core.Globals.SRPTInstancedGlobalNPC
   at Terraria.NPC.GetGlobalNPC[T]() in tModLoader\Terraria\NPC.TML.cs:line 28
   at SRPTerraria.Content.NPCs.Parasites.ParasiteBaseNPC.FindEitherTarget(Int32 SearchRange, Single SearchRangeReduction)
   at SRPTerraria.Content.NPCs.Parasites.ParasiteBaseNPC.Targetlogic(Boolean prioritizeplayer)
   at SRPTerraria.Content.NPCs.Parasites.ParasiteBaseNPC.AI()
   at Terraria.ModLoader.NPCLoader.AI(NPC npc) in tModLoader\Terraria\ModLoader\NPCLoader.cs:line 326
   at Terraria.NPC.UpdateNPC_Inner(Int32 i) in tModLoader\Terraria\NPC.cs:line 73742
   at Terraria.NPC.UpdateNPC(Int32 i) in tModLoader\Terraria\NPC.cs:line 73602
```

This exception occurs when you call `GetGlobalNPC` on an `NPC` which doesn't have an instance of that global. This happens when you return `false` from `SRPTInstancedGlobalNPC.AppliesToEntity` during `SetDefaults` for the `NPC`. 

Either:
- you are calling `GetGlobalNPC` on an `NPC` that you shouldn't be (missing a `Type` check for eg)
- The `NPC` has been 'cleared' (`SetDefaults(0)`)
- Something else on another thread has tampered with the `NPC` while your code was running
  - This seems unlikely, since the exception is thrown on the `Main Thread` after `Entering world with player` but you can try disabling all other mods to be sure.

**Comment by direwolf420** [comment]
The issue is that you forgot to check for `NPC.active` before accessing data on that NPC instance.

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
